
version: '2'

volumes:
  orderer.oil.com:

networks:
  orderer:

services:
  orderer.oil.com:
    container_name: orderer.oil.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/oil.com/orderers/orderer.oil.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 7050:7050
    networks:
      - orderer

  orderer2.oil.com:
    container_name: orderer2.oil.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/oil.com/orderers/orderer2.oil.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 8050:7050
    networks:
      - orderer

  orderer3.oil.com:
    container_name: orderer3.oil.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/oil.com/orderers/orderer3.oil.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 9050:7050
    networks:
      - orderer

  orderer4.oil.com:
    container_name: orderer4.oil.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/oil.com/orderers/orderer4.oil.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 10050:7050
    networks:
      - orderer

  orderer5.oil.com:
    container_name: orderer5.oil.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/oil.com/orderers/orderer5.oil.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 11050:7050
    networks:
      - orderer