version: '2'

volumes:
  orderer.com:

networks:
  petroleum:

services:
  orderer.com:
    container_name: orderer.com
    dns_search: .
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderer.bafs.com/orderers/orderer.orderer.bafs.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 7050:7050
    networks:
      - petroleum

  orderer2.com:
    container_name: orderer2.com
    dns_search: .
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderer.bafs.com/orderers/orderer2.orderer.bafs.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 8050:7050
    networks:
      - petroleum

  orderer3.com:
    container_name: orderer3.com
    dns_search: .
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderer.bafs.com/orderers/orderer3.orderer.bafs.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 9050:7050
    networks:
      - petroleum

  orderer4.com:
    container_name: orderer4.com
    dns_search: .
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderer.bafs.com/orderers/orderer4.orderer.bafs.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 10050:7050
    networks:
      - petroleum

  orderer5.com:
    container_name: orderer5.com
    dns_search: .
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt]
    volumes:
        - ./channel-artifacts:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/orderer.bafs.com/orderers/orderer5.orderer.bafs.com/:/etc/hyperledger/crypto/orderer
    ports:
      - 11050:7050
    networks:
      - petroleum